/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	withFormSchema,
	type IFormSchemaType
} from "@leight/form";
import {
	BankEditFormValueSchema,
	BankEditFormRequestSchema,
	BankEditFormDtoSchema
} from "../../schema";

export type IBankEditFormSchema = IFormSchemaType.of<typeof BankEditFormSchema>;

export const BankEditFormSchema = withFormSchema({
    ValuesSchema:  BankEditFormValueSchema,
    RequestSchema: BankEditFormRequestSchema,
    DtoSchema:     BankEditFormDtoSchema,
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ah48c9hxqn1gvdjtqdsb9wrg = true;