/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type BankSource} from "../../schema";

export type IBankSourceSchema = BankSource["Schema"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_y7l0vubp7pom6xtgj1w5o6s0 = true;