/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITransactionSourceSchemaType} from "../../schema/TransactionSourceSchema";
import {type ISourceMapper} from "@leight/source";

export type ITransactionSourceMapper = ISourceMapper<ITransactionSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_j6q48gpin7qj91dlt6y7p1b3 = true;