/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITransactionKeywordSourceSchemaType} from "../../schema/TransactionKeywordSourceSchema";
import {type ISourceMapper} from "@leight/source";

export type ITransactionKeywordSourceMapper = ISourceMapper<ITransactionKeywordSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_nseii37tvvrawmqasjug0irs = true;