/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IFileSourceSchemaType} from "@leight/file";
import {type ISourceMapper} from "@leight/source";

export type IFileSourceMapper = ISourceMapper<IFileSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_a89ymx6jlalt9ha70u5fmsef = true;