/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_vkn8lra4zz7zda91kqo2qekt = true;

export * from "./container/withLabelRepository";
export * from "./container/withLabelRepositoryContainer";
export * from "./handler/LabelRepositoryHandler";
export * from "./mapper/BaseLabelRepositoryMapper";
export * from "./repository/BaseLabelRepositoryEx";
export * from "./service/BaseLabelRepositoryService";