/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {trpc} from "@monye.one/trpc-client";
import {type IUseCalendarEventInvalidator as IUseInvalidator} from "@monye.one/book";

export const useCalendarEventInvalidator: IUseInvalidator = () => {
    const trpcContext = trpc.useContext();
    return () => {
        trpcContext.book.calendar.event.repository.query.invalidate();
		trpcContext.book.calendar.event.repository.count.invalidate();
    };
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_cr3282p08t059ng7zfk68826 = true;