/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {withUseRepository} from "@leight/source-client";
import {
	type IUseCalendarEventRepository as UseRepository,
	type ICalendarEventSourceSchema as SourceSchema
} from "@monye.one/book";
import {trpc} from "@monye.one/trpc-client";

export const UseCalendarEventRepository: UseRepository = withUseRepository<SourceSchema>(trpc.book.calendar.event.repository);
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_tp56z1buuxtat8ua3owofzfw = true;