/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_i3hwprikrv96egwd18bcey0h = true;

export * from "./context/LabelCreateFormStoreContext";
export * from "./context/LabelCreateMantineFormContext";
export * from "./form/LabelCreateBaseForm";
export * from "./form/LabelCreateInput";
export * from "./form/LabelCreateTrpcForm";
export * from "./selection/LabelMultiSelection";
export * from "./selection/LabelSelection";
export * from "./source/LabelSource";
export * from "./trpc/useLabelInvalidator";
export * from "./trpc/UseLabelRepository";