/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryMapper} from "@leight/source";
import {type TransactionKeywordSource} from "../../schema";

export interface ITransactionKeywordRepositoryMapper extends IRepositoryMapper<TransactionKeywordSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ce9b9syet4io423npm6e8dtf = true;