/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {trpc} from "@monye.one/trpc-client";
import {type IUseFilterInvalidator as IUseInvalidator} from "@leight/filter";

export const useFilterInvalidator: IUseInvalidator = () => {
    const trpcContext = trpc.useContext();
    return () => {
        trpcContext.filter.repository.query.invalidate();
		trpcContext.filter.repository.count.invalidate();
    };
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_bqts26cwsvacndewg1mh86v0 = true;