/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {withRepositoryHandler} from "@leight/trpc-source-server";
import {
	$TransactionRepositoryService,
	type TransactionSource
} from "@monye.one/transaction";

export const TransactionRepositoryHandler = withRepositoryHandler<TransactionSource["Schema"]["Service"]>({
    service: $TransactionRepositoryService,
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_k5kmc472b4bmcmzgtf9uqkqv = true;