/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_xzrswr9znp9l0o50mp3mvzur = true;

export * from "./EntitySource/CalendarEventSource";
export * from "./EntitySource/CalendarEventSourceSchema";