version: '3.4'

x-environment:
  &env
    POSTGRES_USER: monye.one
    POSTGRES_DB: monye.one
    POSTGRES_PASSWORD: 1234

services:
    postgres:
        image: postgres:15.3
        restart: always
        environment: *env
        command: "-c shared_preload_libraries='pg_stat_statements'"
        ports:
            - "127.0.0.1:5632:5432"
        volumes:
            - "postgres:/var/lib/postgresql/data"
        networks:
            - postgres

    edgedb:
        image: edgedb/edgedb:3.0-rc.1
        environment:
            EDGEDB_SERVER_DATABASE: monyeone
            EDGEDB_SERVER_USER: monyeone
            EDGEDB_SERVER_PASSWORD: 1234
            EDGEDB_SERVER_SECURITY: insecure_dev_mode
            EDGEDB_SERVER_TLS_CERT_MODE: generate_self_signed
            EDGEDB_SERVER_ADMIN_UI: enabled
        volumes:
            - "./dbschema:/dbschema"
#            - "edgedb:/var/lib/edgedb/data"
        ports:
            - "127.0.0.1:5656:5656"

volumes:
    postgres:
    edgedb:

networks:
    postgres:
    edgedb:
