/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ISource} from "@leight/source";
import {type ICalendarEventSourceSchema as SourceSchema} from "../schema/ICalendarEventSourceSchema";

export type ICalendarEventSource = ISource<SourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hzij15n78kfioe9nddqj1j9j = true;