/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $FilterRepository = Symbol.for("@leight/filter/IFilterRepository");
export const $FilterRepositoryMapper = Symbol.for("@leight/filter/IFilterRepositoryMapper");
export const $FilterRepositoryService = Symbol.for("@leight/filter/IFilterRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_gcqx90uddnmyw5b257zo4v2i = true;