/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createMantineFormContext} from "@leight/form-client";
import {type ITransactionLabelFormSchemaType} from "@monye.one/transaction";

export const TransactionLabelMantineFormContext = createMantineFormContext<ITransactionLabelFormSchemaType>();
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_mbavc9f7pb85ykjd5axojeek = true;