/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IKeywordSource} from "@leight/keyword";
import {KeywordSourceEx} from "../../source";

export class KeywordSource extends KeywordSourceEx implements IKeywordSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_l8p5sk6d2jqo0if3tmewqc7k = true;