/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createMantineFormContext} from "@leight/form-client";
import {type IBankEditFormSchema} from "@monye.one/bank";

export const BankEditMantineFormContext = createMantineFormContext<IBankEditFormSchema>();
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_wi8klf6z1pt9r1euc4ud3qsm = true;