/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type IBankEditFormSchemaType} from "@monye.one/bank";

export const BankEditFormStoreContext = createFormContext<IBankEditFormSchemaType>({
    name: "BankEditForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_pb6zlmjijajxn7b5303tdyra = true;