/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type IBankPatchFormSchemaType} from "@monye.one/bank";

export const BankPatchFormStoreContext = createFormContext<IBankPatchFormSchemaType>({
    name: "BankPatchForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_yxjzwif0zxcjh19zg0v74s2c = true;