/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type IBankEditFormSchema} from "../api/BankEditFormTypes";

export const BankEditFormStoreContext = createFormContext<IBankEditFormSchema>({
    name: "BankEditForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_wbvx4n0opalrc2hj4xiqt1dn = true;