/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ICalendarEventSourceSchemaType} from "@monye.one/book";
import {type ISourceMapper} from "@leight/source";

export type ICalendarEventSourceMapper = ISourceMapper<ICalendarEventSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_rhdzrwg7azf1q5h6y7kujusg = true;