/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ICalendarEventSourceSchema} from "@monye.one/book";
import {type ISourceMapper} from "@leight/source-server";

export type ICalendarEventSourceMapper = ISourceMapper<ICalendarEventSourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_z0vr5lo2x2u3s3tbc24v9m9v = true;