/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IJobSourceSchema} from "@leight/job";
import {type ISourceMapper} from "@leight/source-server";

export type IJobSourceMapper = ISourceMapper<IJobSourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_zwcf886ojs2ca0335me1ju0p = true;