/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IJobSourceSchemaType} from "@leight/job";
import {type ISourceMapper} from "@leight/source";

export type IJobSourceMapper = ISourceMapper<IJobSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_x0ons854r2phr1yiqnnt2lp3 = true;