/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IMantineFormContext,
	type InferFormSchemas,
	type IFormInputsFactory
} from "@leight/form-client";
import {BankEditFormSchema} from "../../schema";

export type IBankEditFormSchema = InferFormSchemas<typeof BankEditFormSchema>;
export type IBankEditMantineFormContext = IMantineFormContext<IBankEditFormSchema>;
export type IBankEditFormInputFactory = IFormInputsFactory<IBankEditFormSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_usodxaiiia2ycyxnma2197tc = true;