/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IBankSourceMapper} from "@monye.one/bank";
import {BankSourceMapperEx} from "../../source";

export class BankSourceMapper extends BankSourceMapperEx implements IBankSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_goga396b8wr1oyusrl0lwaua = true;