/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_c054o7xo0a4a4lpx7kp7eizh = true;

export * from "./index";
export * from "./repository/IUseCalendarEventRepository";
export * from "./repository/IUseCalendarEventRepositoryQuery";
export * from "./schema/ICalendarEventSourceSchema";
export * from "./source/ICalendarEventSource";
export * from "./source/ICalendarEventSourceType";
export * from "./source/IUseCalendarEventInvalidator";