/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_o6pqd14r9060mp6kndn57sv9 = true;

export * from "./api/BankCreateFormTypes";
export * from "./api/BankEditFormTypes";
export * from "./api/BankPatchFormTypes";
export * from "./api/BankTypes";
export * from "./schema/BankPrismaSchema";
export * from "./Source/BankPrismaSource";