/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryMapper} from "@leight/source";
import {type FilterSource} from "../../schema";

export interface IFilterRepositoryMapper extends IRepositoryMapper<FilterSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_p9bt2ju671oxc1jvlicog6b8 = true;