/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_p6f9suwk9kygyrquopt2rj35 = true;

export * from "./Source/UserBasePrismaSource";
export * from "./SourceMapper/UserBaseSourceMapper";
export * from "./SourceService/UserBaseSourceService";