/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUserSource} from "@leight/user";
import {UserSourceEx} from "../source";

export class UserSource extends UserSourceEx implements IUserSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_slpv1m4ogjs48k9pheenje09 = true;