/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractRepositoryMapper} from "@leight/source-server";
import {type TransactionSource} from "@monye.one/transaction";

export class BaseTransactionRepositoryMapper extends AbstractRepositoryMapper<TransactionSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_qyg0e34knoqryf6bjo0e9uuh = true;