/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type ILabelPatchFormSchemaType} from "@leight/label";

export const LabelPatchFormStoreContext = createFormContext<ILabelPatchFormSchemaType>({
    name: "LabelPatchForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_do9j7piv1g3qoc9x75xbe4j2 = true;