/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryMapper} from "@leight/source";
import {type CalendarEventSource} from "../../schema";

export interface ICalendarEventRepositoryMapper extends IRepositoryMapper<CalendarEventSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ubk27enfywi2nj7y0ss9nu1i = true;