/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITransactionKeywordSourceMapper} from "@monye.one/transaction";
import {TransactionKeywordBaseSourceMapper} from "./TransactionKeywordBaseSourceMapper";

export class TransactionKeywordSourceMapper extends TransactionKeywordBaseSourceMapper implements ITransactionKeywordSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_kzgadfxiy6juxg160juktp3v = true;