/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITransactionSourceMapper} from "@monye.one/transaction";
import {TransactionBaseSourceMapper} from "./TransactionBaseSourceMapper";

export class TransactionSourceMapper extends TransactionBaseSourceMapper implements ITransactionSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_m3p5tbqkrktow0h2q0sxlurr = true;