/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceMapper} from "@leight/source-server";
import {
	type IFilterSourceSchemaType,
	type IFilterSourceMapper
} from "@leight/filter";

export class FilterBaseSourceMapper extends AbstractSourceMapper<IFilterSourceSchemaType> implements IFilterSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_gid3fnm6i2snpbdv5x7p0vgf = true;