/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	withSourceSchemaEx,
	type ISourceSchemaExType
} from "@leight/source";
import {
	LabelWhereInputSchema,
	LabelWhereUniqueInputSchema,
	LabelOrderByWithRelationInputSchema
} from "@leight/prisma";

export type ILabelPrismaSchemaType = ISourceSchemaExType.of<typeof LabelPrismaSchema>;

export const LabelPrismaSchema = withSourceSchemaEx({
    WhereSchema:       LabelWhereInputSchema,
    WhereUniqueSchema: LabelWhereUniqueInputSchema,
    OrderBySchema:     LabelOrderByWithRelationInputSchema,
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_d5swlf33z4cmm4rnwewbegno = true;