/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $CalendarEventRepository = Symbol.for("@monye.one/book/ICalendarEventRepository");
export const $CalendarEventRepositoryMapper = Symbol.for("@monye.one/book/ICalendarEventRepositoryMapper");
export const $CalendarEventRepositoryService = Symbol.for("@monye.one/book/ICalendarEventRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_b1pi1tw2mqx2u0bhfk5417ew = true;