/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type IBankCreateFormSchemaType} from "@monye.one/bank";

export const BankCreateFormStoreContext = createFormContext<IBankCreateFormSchemaType>({
    name: "BankCreateForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_t1ndb1plnly6op0f8ptj90m7 = true;