/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceMapper} from "@leight/source-server";
import {
	type ILabelSourceSchemaType,
	type ILabelSourceMapper
} from "@leight/label";

export class LabelBaseSourceMapper extends AbstractSourceMapper<ILabelSourceSchemaType> implements ILabelSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_c7h21hsakztn03fqqky84vsv = true;