/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IQueryProviderProps,
	QueryProvider
} from "@leight/source-client";
import {type ICalendarEventSourceSchema as SourceSchema} from "@monye.one/book";
import {type FC} from "react";
import {CalendarEventSource as Source} from "../source/CalendarEventSource";

export interface ICalendarEventQueryProviderProps extends Omit<IQueryProviderProps<SourceSchema>, "QueryContext"> {
}

/**
 * Provides all Query parts for CalendarEvent used in fetching and sorting its data. 
 */
export const CalendarEventQueryProvider: FC<ICalendarEventQueryProviderProps> = props => {
    return <QueryProvider<SourceSchema>
        QueryContext={Source.query}
        {...props}
    />;
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_qkrs3xltzsfk3lmlq5yb9db9 = true;