/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IFormSchemaType} from "@leight/form";
import {
	type ISourceMultiSelectProps,
	SourceMultiSelect
} from "@leight/form-client";
import {LabelMultiSelection} from "../Selection/LabelMultiSelection";
import {LabelSourceStore} from "../Source/LabelSourceStore";
import {type ILabelSourceSchemaType} from "@leight/label";

export interface ILabelMultiSourceSelect<TFormSchemaType extends IFormSchemaType> extends Omit<ISourceMultiSelectProps<TFormSchemaType, ILabelSourceSchemaType>, "SelectionContext" | "SourceStore"> {
}

export const LabelMultiSourceSelect = <TFormSchemaType extends IFormSchemaType>(props: ILabelMultiSourceSelect<TFormSchemaType>) => {
    return <SourceMultiSelect<TFormSchemaType, ILabelSourceSchemaType>
        SelectionContext={LabelMultiSelection}
        SourceStore={LabelSourceStore}
        {...props}
    />
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_bnxsuyztpqmt0g3pz5apqgcs = true;