import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IGeneratorServerPrismaSourceParams {
    entities: IGeneratorServerPrismaSourceParams.IEntity[];
}

export namespace IGeneratorServerPrismaSourceParams {
    export interface IEntity {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Name of prisma "repository" (to generate prismaClient.<prisma> calls); usually snakeCase model name.
         */
        prisma: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
        /**
         * Prisma package which exports PrismaClient.
         */
        prisma: string;
    }
}

export const generatorServerPrismaSource: IGenerator<IGeneratorServerPrismaSourceParams> = async (
    {
        barrel,
        folder,
        params: {entities},
    }) => {
    const file = withSourceFile();

    entities.forEach(({name, prisma, packages}) => {
        file.withHeader(`
    Base Prisma Source contains default implementation of Source for entity ${name} connected to Prisma. This could be used for further extensions,
    also default export uses this as a parent class.
        `);

        file.withImports({
                imports: {
                    "@leight/query":         [
                        "withCursor",
                    ],
                    "@leight/prisma":        [
                        "$PrismaClient",
                    ],
                    "@leight/source":        [
                        "type ISource",
                        "withUpsert",
                    ],
                    "@leight/source-server": [
                        "AbstractSource",
                    ],
                },
            })
            .withImports({
                imports: {
                    [packages.schema]: [
                        `$${name}Source`,
                        `type I${name}Where`,
                        `type I${name}WhereUnique`,
                        `type I${name}OrderBy`,
                        `type I${name}SourceSchema`,
                    ],
                },
            })
            .withImports({
                imports: {
                    [packages.prisma]: [
                        "type PrismaClient",
                    ],
                },
            })
            .withClasses({
                exports: {
                    [`${name}BasePrismaSource`]: {
                        extends: `AbstractSource<I${name}SourceSchema>`,
                        body:    `
    static inject = [
        $PrismaClient,
    ];

    constructor(
        protected prismaClient: PrismaClient,
    ) {
        super($${name}Source);
    }

    async runUpsert(props: ISource.IUpsert<I${name}SourceSchema>): Promise<I${name}SourceSchema["Entity"]> {
        return this.prisma().upsert(withUpsert(props));
    }

    async runCount(query?: I${name}SourceSchema["Query"]): Promise<number> {
        return this.prisma().count({
            where: this.toWhere(query?.filter),
        });
    }

    async runQuery(query?: I${name}SourceSchema["Query"]): Promise<I${name}SourceSchema["Entity"][]> {
        return this.prisma().findMany(withCursor({
            query,
            arg: {
                where:   this.toWhere(query?.filter),
                orderBy: this.toOrderBy(query?.sort),
            }
        }));
    }
    
    prisma() {
        return this.prismaClient.${prisma};
    }
    
    toWhere(filter?: I${name}SourceSchema["Filter"]): I${name}Where | undefined {
        return undefined;
    }
    
    toWhereUnique(filter?: I${name}SourceSchema["Filter"]): I${name}WhereUnique | undefined {
        return undefined;
    }
    
    toOrderBy(sort?: I${name}SourceSchema["Sort"]): I${name}OrderBy | undefined {
        return sort as I${name}OrderBy;
    }
                    `,
                    },
                },
            });
    });

    file.saveTo({
        file: normalize(`${process.cwd()}/${folder}/ServerPrismaSource.ts`),
        barrel,
    });
};
