import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IGeneratorServerTrpcSourceParams {
    entities: IGeneratorServerTrpcSourceParams.IEntity[];
}

export namespace IGeneratorServerTrpcSourceParams {
    export interface IEntity {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }
}

export const generatorServerTrpcSource: IGenerator<IGeneratorServerTrpcSourceParams> = async (
    {
        barrel,
        directory,
        params: {entities},
    }) => {
    entities.forEach(({name, packages}) => {
        withSourceFile()
            .withImports({
                imports: {
                    "@leight/trpc-source-server": [
                        "withSourceProcedure",
                    ],
                }
            })
            .withImports({
                imports: {
                    [packages.schema]: [
                        `$${name}SourceService`,
                        `type I${name}SourceSchemaType`,
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`${name}SourceProcedure`]: {
                        body: `
withSourceProcedure<I${name}SourceSchemaType>({
    sourceService: $${name}SourceService,
})
                    `,
                    },
                },
            })
            .saveTo({
                file: normalize(`${directory}/ServerTrpc/${name}Trpc.ts`),
                barrel,
            });
    });
};
