import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IWithRepositoryServiceParams {
    repositories: IWithRepositoryServiceParams.IRepository[];
}

export namespace IWithRepositoryServiceParams {
    export interface IRepository {
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (IRepository implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }

}

export const withRepositoryService: IGenerator<IWithRepositoryServiceParams> = async (
    {
        barrel,
        directory,
        params: {repositories},
    }) => {
    repositories.forEach(({name, packages}) => {
        withSourceFile()
            .withImports({
                imports: {
                    "@leight/source-server": [
                        "AbstractRepositoryService",
                    ],
                    "@leight/source":        [
                        "type IRepositoryService",
                        "type IRepositoryMapper",
                        "type IRepository",
                    ],
                    [packages.schema]:       [
                        `$${name}Source`,
                        `$${name}SourceMapper`,
                        `type I${name}SourceSchemaType`,
                    ],
                },
            })
            .withInterfaces({
                exports: {
                    [`I${name}RepositoryService`]: {
                        extends: [
                            {
                                type: `IRepositoryService<I${name}SourceSchemaType>`,
                            },
                        ],
                    },
                },
            })
            .withClasses({
                exports: {
                    [`Base${name}RepositoryService`]: {
                        implements: `I${name}RepositoryService`,
                        extends:    `AbstractRepositoryService<I${name}SourceSchemaType>`,
                        body:       `
static inject = [
        $${name}Source,
        $${name}SourceMapper,
    ];
    
    constructor(
        protected $source: IRepository<I${name}SourceSchemaType>,
        protected $mapper: IRepositoryMapper<I${name}SourceSchemaType>,
    ) {
        super();
    }
    
    source(): IRepository<I${name}SourceSchemaType> {
        return this.$source;
    }
    
    mapper(): IRepositoryMapper<I${name}SourceSchemaType> {
        return this.$mapper;
    }
                        `
                    },
                },
            })
            .saveTo({
                file: normalize(`${directory}/service/Base${name}RepositoryService.ts`),
                barrel,
            });
    });
};
