import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IWithRepositoryParams {
    repositories: IWithRepositoryParams.IRepository[];
}

export namespace IWithRepositoryParams {
    export interface IRepository {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }
}

export const withRepository: IGenerator<IWithRepositoryParams> = async (
    {
        barrel,
        directory,
        params: {repositories},
    }) => {
    repositories.forEach(({name, packages}) => {
        withSourceFile()
            .withImports({
                imports: {
                    "@leight/source-server": [
                        "AbstractRepository",
                    ],
                },
            })
            .withImports({
                imports: {
                    [packages.schema]: [
                        `$${name}Repository`,
                        `type ${name}Source`,
                    ],
                }
            })
            .withClasses({
                exports: {
                    [`Base${name}Repository`]: {
                        extends: `AbstractRepository<${name}Source["Schema"]["Repository"]>`,
                        body:    `
    constructor() {
        super($${name}Repository);
    }
                    `,
                    },
                },
            })
            .saveTo({
                file: normalize(`${directory}/repository/Base${name}Repository.ts`),
                barrel,
            });
    });
};
