/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceService} from "@leight/source-server";
import {
	type ISourceService,
	type ISourceMapper,
	type ISource
} from "@leight/source";
import {
	$TransactionSource,
	$TransactionSourceMapper,
	type ITransactionSourceSchema
} from "@monye.one/transaction";

export interface ITransactionBaseSourceService extends ISourceService<ITransactionSourceSchema> {
}

export class TransactionSourceService extends AbstractSourceService<ITransactionSourceSchema> implements ITransactionBaseSourceService {
	static inject = [
        $TransactionSource,
        $TransactionSourceMapper,
    ];
    
    constructor(
        protected $source: ISource<ITransactionSourceSchema>,
        protected $mapper: ISourceMapper<ITransactionSourceSchema>,
    ) {
        super();
    }
    
    source(): ISource<ITransactionSourceSchema> {
        return this.$source;
    }
    
    mapper(): ISourceMapper<ITransactionSourceSchema> {
        return this.$mapper;
    }
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_antoxl09ynk9g7dfx73gcga0 = true;