/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IContainer} from "@leight/container";
import {ServiceContext} from "@leight/container-server";
import {
	type ICalendarEventRepository,
	type ICalendarEventRepositoryService,
	type ICalendarEventRepositoryMapper,
	$CalendarEventRepository,
	$CalendarEventRepositoryMapper,
	$CalendarEventRepositoryService
} from "@monye.one/book";

export const CalendarEventRepositoryContext = (container: IContainer) => new ServiceContext<ICalendarEventRepository>(container, $CalendarEventRepository);
export const CalendarEventRepositoryMapperContext = (container: IContainer) => new ServiceContext<ICalendarEventRepositoryMapper>(container, $CalendarEventRepositoryMapper);
export const CalendarEventRepositoryServiceContext = (container: IContainer) => new ServiceContext<ICalendarEventRepositoryService>(container, $CalendarEventRepositoryService);
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_vzxnyyc8zh84ivbfochm3og4 = true;