/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IContainer,
	ServiceContext
} from "@leight/container";
import {
	type IJobRepository,
	type IJobRepositoryService,
	type IJobRepositoryMapper,
	$JobRepository,
	$JobRepositoryMapper,
	$JobRepositoryService
} from "@leight/job";

export const withJobRepository = (container: IContainer) => new ServiceContext<IJobRepository>(container, $JobRepository).resolve();
export const withJobRepositoryMapper = (container: IContainer) => new ServiceContext<IJobRepositoryMapper>(container, $JobRepositoryMapper).resolve();
export const withJobRepositoryService = (container: IContainer) => new ServiceContext<IJobRepositoryService>(container, $JobRepositoryService).resolve();
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_w3vt6adgk28zls4gb0t4kkqj = true;