/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	SourceTable,
	type ISourceTableInternalProps
} from "@leight/table-client";
import {
	type ITransactionSourceSchema,
	TransactionSchema
} from "@monye.one/transaction";
import {
	TransactionSourceStore,
	TransactionSortStore
} from "./ClientStore";
import {TransactionSource} from "./ClientSourceProvider";

export interface ITransactionSourceTableInternalProps<TColumnKeys extends string> extends Omit<ISourceTableInternalProps<ITransactionSourceSchema, TColumnKeys>, "useSource" | "useSort" | "schema"> {
}

export interface ITransactionSourceTableProps<TColumnKeys extends string> extends Omit<ITransactionSourceTableInternalProps<TColumnKeys>, "columns" | "withTranslation"> {
}

export const TransactionSourceTable = <TColumnKeys extends string>(props: ITransactionSourceTableInternalProps<TColumnKeys>) => {
    return <TransactionSource>
        <SourceTable
            useSource={TransactionSourceStore.useState}
            useSort={TransactionSortStore.useState}
            schema={TransactionSchema}
            {...props}
        />
    </TransactionSource>;
};