/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IBankSourceMapper} from "../api";
import {AbstractSourceMapper} from "@leight/source-server";
import {type IBankSourceSchema} from "@monye.one/bank";

export class BankBaseSourceMapper extends AbstractSourceMapper<IBankSourceSchema> implements IBankSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ztf2uckvm6wju5kik95u7yez = true;