import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IGeneratorClientTrpcSourceParams {
    entities: IGeneratorClientTrpcSourceParams.IEntity[];
}

export namespace IGeneratorClientTrpcSourceParams {
    export interface IEntity {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
        trpc: ITrpc;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }

    export interface ITrpc {
        /**
         * Package (import) of client-side TRPC (should export named trpc)
         */
        package: string;
        /**
         * Part of the trpc call chain (base is `trpc`.${trpcPath}.`...rest of standard trpc router`
         */
        path: string;
    }
}

export const generatorClientTrpcSource: IGenerator<IGeneratorClientTrpcSourceParams> = async (
    {
        barrel,
        directory,
        params: {entities}
    }) => {
    entities.forEach((
        {
            name,
            trpc,
            packages
        }) => {
        withSourceFile()
            .withImports({
                imports: {
                    "@leight/source-client": [
                        "withSourceQuery",
                    ],
                    [packages.schema]:       [
                        `type I${name}SourceSchemaType`,
                        `type IUse${name}SourceQuery`,
                    ],
                }
            })
            .withImports({
                imports: {
                    [trpc.package]: [
                        "trpc",
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`Use${name}SourceQuery`]: {
                        type: `IUse${name}SourceQuery`,
                        body: `withSourceQuery<I${name}SourceSchemaType>(trpc.${trpc.path}.source)`,
                    },
                }
            })
            .saveTo({
                file: normalize(`${directory}/trpc/Use${name}SourceQuery.tsx`),
                barrel,
            });
    });
};
