import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IGeneratorClientSourceProviderParams {
    entities: IGeneratorClientSourceProviderParams.IEntity[];
}

export namespace IGeneratorClientSourceProviderParams {
    export interface IEntity {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }
}

export const generatorClientSourceProvider: IGenerator<IGeneratorClientSourceProviderParams> = async (
    {
        barrel,
        directory,
        params: {entities}
    }) => {
    entities.forEach(({name, packages}) => {
        withSourceFile()
            .withImports({
                imports: {
                    "@leight/source-client":  [
                        "type IQueryProviderProps",
                        "QueryProvider",
                    ],
                    [packages.schema]:        [
                        `type I${name}SourceSchemaType`,
                    ],
                    "react":                  [
                        "type FC",
                    ],
                    [`./${name}SourceStore`]: [
                        `${name}SourceStore`,
                    ],
                }
            })
            .withInterfaces({
                exports: {
                    [`I${name}QueryProviderProps`]: {
                        extends: [
                            {type: `IQueryProviderProps<I${name}SourceSchemaType>`},
                        ],
                    },
                },
            })
            .withConsts({
                exports: {
                    [`${name}QueryProvider`]: {
                        type:    `FC<I${name}QueryProviderProps>`,
                        comment: `
/**
 * Provides all Query parts for ${name} used in fetching and sorting its data. 
 */
                        `,
                        body:    `props => {
    return <QueryProvider<I${name}SourceSchemaType>
        SourceStore={${name}SourceStore}
        {...props}
    />;
}
                    `,
                    },
                }
            })
            .saveTo({
                file: normalize(`${directory}/Source/${name}QueryProvider.tsx`),
                barrel,
            });
    });
};
