import {withSourceFile}  from "@leight/generator-server";
import {normalize}       from "node:path";
import {type IGenerator} from "../../api";

export interface IWithSourceParams {
    sources: IWithSourceParams.ISource[];
}

export namespace IWithSourceParams {
    export interface ISource {
        /**
         * Base name exported (used to name all exported objects)
         */
        name: string;
        /**
         * Required package imports
         */
        packages: IPackages;
    }

    export interface IPackages {
        /**
         * Package used to import all schema-related types (ISource implementation, IWhere and so on, can be generated by @leight).
         */
        schema: string;
    }
}

export const withSource: IGenerator<IWithSourceParams> = async (
    {
        barrel,
        directory,
        params: {sources}
    }) => {
    sources.forEach(({
                         name,
                         packages
                     }) => {
        console.log(`- Generating [withSource] [${name}]`);

        withSourceFile()
            .withHeader(`
    Source code containing improved Zustand store stuff for Source support (client-side).
        `)
            .withImports({
                imports: {
                    "@leight/source-client": [
                        "withSource",
                    ],
                    [packages.schema]:       [
                        `${name}SourceSchema as SourceSchema`,
                        `type ${name}Source as Source`,
                    ],
                },
            })
            .withImports({
                imports: {
                    [`../Trpc/Use${name}SourceQuery`]:      [
                        `Use${name}SourceQuery`,
                    ],
                    [`../Trpc/use${name}QueryInvalidator`]: [
                        `use${name}QueryInvalidator`,
                    ],
                },
            })
            .withConsts({
                exports: {
                    [`${name}Source`]: {
                        body: `
withSource<Source>({
    name: "${name}",
    schema: SourceSchema,
    use: Use${name}SourceQuery,
    useInvalidator: use${name}QueryInvalidator,
})
                    `,
                    },
                },
            })
            .saveTo({
                file: normalize(`${directory}/source/${name}Source.ts`),
                barrel,
            });
    });
};
