/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryMapper} from "@leight/source";
import {type FileSource} from "../../schema/FileSource";

export interface IFileRepositoryMapper extends IRepositoryMapper<FileSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_dx4p8aymid6dimql4wyxggow = true;