/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_nmwre2as6o81o76bdt32tgj6 = true;

export * from "./repository/IUserRepository";
export * from "./schema/UserRepositorySchemaEx";
export * from "./symbol/UserRepositorySymbol";