/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_svv834af1yf7o7f0kzijaii5 = true;

export * from "./index";
export * from "./mapper/IUserRepositoryMapper";
export * from "./repository/IUserRepository";
export * from "./repository/IUseUserRepository";
export * from "./repository/UseUserRepositoryQuery";
export * from "./schema/IUserSourceSchema";
export * from "./schema/UserRepositorySchemaEx";
export * from "./source/IUserSource";
export * from "./source/IUserSourceType";
export * from "./source/IUseUserInvalidator";
export * from "./symbol/UserRepositorySymbol";