/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IContainer} from "@leight/container";
import {ServiceContext} from "@leight/container-server";
import {
	type IBankRepository,
	type IBankRepositoryService,
	type IBankRepositoryMapper,
	$BankRepository,
	$BankRepositoryMapper,
	$BankRepositoryService
} from "@monye.one/bank";

export const BankRepositoryContext = (container: IContainer) => new ServiceContext<IBankRepository>(container, $BankRepository);
export const BankRepositoryMapperContext = (container: IContainer) => new ServiceContext<IBankRepositoryMapper>(container, $BankRepositoryMapper);
export const BankRepositoryServiceContext = (container: IContainer) => new ServiceContext<IBankRepositoryService>(container, $BankRepositoryService);
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_rl70ussbz4ibhavvm7czmnh2 = true;