/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_qmdbv6s9ko32pl2uypgx40l6 = true;

export * from "./ServerTrpc/BankTrpcRouter";
export * from "./ServerTrpc/CalendarEventTrpcRouter";
export * from "./ServerTrpc/JobTrpcRouter";
export * from "./ServerTrpc/TransactionTrpcRouter";