/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {withSourceProcedure} from "@leight/trpc-source-server";
import {
	$FilterSourceService,
	type IFilterSourceSchemaType
} from "@leight/filter";

export const FilterSourceProcedure = withSourceProcedure<IFilterSourceSchemaType>({
    sourceService: $FilterSourceService,
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_exrxpur2nr1ah6c08vb9nffe = true;