/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IQueryProviderProps,
	QueryProvider
} from "@leight/source-client";
import {type LabelSource as Source} from "@leight/label";
import {type FC} from "react";
import {LabelSource} from "../source/LabelSource";

export interface ILabelQueryProviderProps extends Omit<IQueryProviderProps<Source>, "QueryContext"> {
}

/**
 * Provides all Query parts for Label used in fetching and sorting its data. 
 */
export const LabelQueryProvider: FC<ILabelQueryProviderProps> = props => {
    return <QueryProvider<Source>
        QueryContext={LabelSource.query}
        {...props}
    />;
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_b9xzgsnzu84umtbp8rsr959i = true;