/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IBankSource} from "@monye.one/bank";
import {BankBaseSource} from "./ServerBaseSource";

export class BankSource extends BankBaseSource implements IBankSource {
}