/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IBankSource} from "@monye.one/bank";
import {BankSourceEx} from "../source";

export class BankSource extends BankSourceEx implements IBankSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_uzz6mt5cos8j1b8lwkfw3gks = true;