/**
	This is a file generated by MCP (managed code pattern) approach.

    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {BankSourceMapperEx} from "../source/BankSourceMapperEx";
import {IBankSourceMapper}  from "./ServerSource";

export class BankSourceMapper extends BankSourceMapperEx implements IBankSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_e1kslgbpw2iylzf19vf8qt88 = true;
