/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_so6tbvp3hdwpao0bohdh24wa = true;

export * from "./Source/FilePrismaSchema";
export * from "./Source/FilePrismaSource";
export * from "./Source/FileSchema";