/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_cblagnegpcakaf3caxy4zqqa = true;

export * from "./index";
export * from "./api/FileTypes";
export * from "./schema/FilePrismaSchema";
export * from "./Source/FilePrismaSource";