/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractRepositoryService} from "@leight/source-server";
import {
	type IRepositoryService,
	type IRepositoryMapper,
	type IRepository
} from "@leight/source";
import {
	$FilterSource,
	$FilterSourceMapper,
	type IFilterSourceSchemaType
} from "@leight/filter";

export interface IFilterRepositoryService extends IRepositoryService<IFilterSourceSchemaType> {
}

export class BaseFilterRepositoryService extends AbstractRepositoryService<IFilterSourceSchemaType> implements IFilterRepositoryService {
	static inject = [
        $FilterSource,
        $FilterSourceMapper,
    ];
    
    constructor(
        protected $source: IRepository<IFilterSourceSchemaType>,
        protected $mapper: IRepositoryMapper<IFilterSourceSchemaType>,
    ) {
        super();
    }
    
    source(): IRepository<IFilterSourceSchemaType> {
        return this.$source;
    }
    
    mapper(): IRepositoryMapper<IFilterSourceSchemaType> {
        return this.$mapper;
    }
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_s5l0mg0dkjdc46f7xqlwsjd4 = true;