/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	SourceTable,
	type ISourceTableInternalProps
} from "@leight/table-client";
import {
	type IBankSourceSchema,
	BankSchema
} from "@monye.one/bank";
import {
	BankSourceStore,
	BankSortStore
} from "./ClientStore";
import {BankSource} from "./ClientSourceProvider";

export interface IBankSourceTableInternalProps<TColumnKeys extends string> extends Omit<ISourceTableInternalProps<IBankSourceSchema, TColumnKeys>, "useSource" | "useSort" | "schema"> {
}

export interface IBankSourceTableProps<TColumnKeys extends string> extends Omit<IBankSourceTableInternalProps<TColumnKeys>, "columns" | "withTranslation"> {
}

export const BankSourceTable = <TColumnKeys extends string>(props: IBankSourceTableInternalProps<TColumnKeys>) => {
    return <BankSource>
        <SourceTable
            useSource={BankSourceStore.useState}
            useSort={BankSortStore.useState}
            schema={BankSchema}
            {...props}
        />
    </BankSource>;
};