/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_z94yte19sikzeqcl8hrgte0i = true;

export * from "./api/BankCreateFormTypes";
export * from "./api/BankEditFormTypes";
export * from "./api/BankPatchFormTypes";
export * from "./ClientForm/BankCreateBaseForm";
export * from "./ClientForm/BankCreateInput";
export * from "./ClientForm/BankEditBaseForm";
export * from "./ClientForm/BankEditInput";
export * from "./ClientForm/BankPatchBaseForm";
export * from "./ClientForm/BankPatchInput";
export * from "./ClientSource/BankQueryProvider";
export * from "./ClientSource/BankSource";
export * from "./ClientSource/BankSourceStore";
export * from "./ClientTable/BankSourceTable";
export * from "./ClientTrpc/BankCreateTrpcForm";
export * from "./ClientTrpc/BankEditTrpcForm";
export * from "./ClientTrpc/BankPatchTrpcForm";
export * from "./ClientTrpc/useBankQueryInvalidator";
export * from "./ClientTrpc/UseBankSourceQuery";
export * from "./FormStoreContext/BankCreateFormStoreContext";
export * from "./FormStoreContext/BankCreateMantineFormContext";
export * from "./FormStoreContext/BankEditFormStoreContext";
export * from "./FormStoreContext/BankEditMantineFormContext";
export * from "./FormStoreContext/BankPatchFormStoreContext";
export * from "./FormStoreContext/BankPatchMantineFormContext";