apiVersion: 1

datasources:
    - name: Loki
      type: loki
      access: proxy
      isDefault: true
      editable: true
      url: http://loki:3100

    - name: Prometheus
      type: prometheus
      access: proxy
      editable: true
      url: http://prometheus:9090
