module.exports = {
    extends: [
        "eslint:recommended",
        "next",
        "airbnb",
        "airbnb-typescript",
        "prettier",
        "turbo",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
    ],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "./tsconfig.json",
    },
    plugins: ["@typescript-eslint", "eslint-plugin-unicorn"],
    rules: {
        "import/prefer-default-export": "off",
        "react/react-in-jsx-scope": "off",
        "no-console": "off",
        "import/extensions": "off",
        "arrow-body-style": "off",
        "react/jsx-curly-brace-presence": "off",
        "react/jsx-props-no-spreading": "off",
        "react/function-component-definition": "off",
        "no-underscore-dangle": "off",
        "class-methods-use-this": "off",
        "@typescript-eslint/no-empty-interface": "off",
        "react-hooks/exhaustive-deps": "off",
        "no-unused-vars": "off",
        "react/prop-types": "off",
        "react/require-default-props": "off",
        "react/jsx-no-useless-fragment": "off",
        "no-html-link-for-pages": "off",
        "no-await-in-loop": "off",
        "no-plusplus": "off",
        "@typescript-eslint/no-namespace": "off",
        "no-restricted-syntax": "off",
        "@typescript-eslint/no-unused-expressions": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/no-loop-func": "off",
        "no-continue": "off",
        "import/no-extraneous-dependencies": [
            "error",
            { devDependencies: true },
        ],
    },
};
