/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IMantineFormContext} from "@leight/form";
import {type ITransactionFilterFormSchemaType} from "../../schema/TransactionFilterFormSchema";

export type ITransactionFilterMantineFormContext = IMantineFormContext<ITransactionFilterFormSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_b5pggps4x7afx5wjrv07tktz = true;