/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type FilterSource} from "../../schema";

export type IUseFilterInvalidator = FilterSource["Type"]["UseInvalidator"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_z1oxp2smp8nlc2ou5bd87zox = true;