/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUserSourceMapper} from "@leight/user";
import {UserBaseSourceMapper} from "./UserBaseSourceMapper";

export class UserSourceMapper extends UserBaseSourceMapper implements IUserSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_bf47wikhp0rauct3j1f0gh1v = true;