/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceMapper} from "@leight/source-server";
import {
	type IUserSourceSchemaType,
	type IUserSourceMapper
} from "@leight/user";

export class UserBaseSourceMapper extends AbstractSourceMapper<IUserSourceSchemaType> implements IUserSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_c2uk6jz35rp926dpet80e6im = true;