/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_vrf0ffbvkflnv4rn0f7e6p5r = true;

export * from "./index";
export * from "./mapper/ILabelRepositoryMapper";
export * from "./repository/ILabelRepository";
export * from "./repository/IUseLabelRepository";
export * from "./repository/IUseLabelRepositoryQuery";
export * from "./schema/ILabelSourceSchema";
export * from "./schema/LabelRepositorySchemaEx";
export * from "./source/ILabelSource";
export * from "./source/ILabelSourceType";
export * from "./source/IUseLabelInvalidator";
export * from "./symbol/LabelRepositorySymbol";