/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IContainer} from "@leight/container";
import {ServiceContext} from "@leight/container-server";
import {
	IUserRepositoryEx,
	type IUserRepositoryService,
	type IUserRepositoryMapper,
	$UserRepository,
	$UserRepositoryMapper,
	$UserRepositoryService
} from "@leight/user";

export const UserRepositoryContext = (container: IContainer) => new ServiceContext<IUserRepositoryEx>(container, $UserRepository);
export const UserRepositoryMapperContext = (container: IContainer) => new ServiceContext<IUserRepositoryMapper>(container, $UserRepositoryMapper);
export const UserRepositoryServiceContext = (container: IContainer) => new ServiceContext<IUserRepositoryService>(container, $UserRepositoryService);
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_mm0auk4vm1zmwyo48rl7jkap = true;