/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IContainer} from "@leight/container";
import {ServiceContext} from "@leight/container-server";
import {
	type ITransactionKeywordRepository,
	type ITransactionKeywordRepositoryService,
	type ITransactionKeywordRepositoryMapper,
	$TransactionKeywordRepository,
	$TransactionKeywordRepositoryMapper,
	$TransactionKeywordRepositoryService
} from "@monye.one/transaction";

export const TransactionKeywordRepositoryContext = (container: IContainer) => new ServiceContext<ITransactionKeywordRepository>(container, $TransactionKeywordRepository);
export const TransactionKeywordRepositoryMapperContext = (container: IContainer) => new ServiceContext<ITransactionKeywordRepositoryMapper>(container, $TransactionKeywordRepositoryMapper);
export const TransactionKeywordRepositoryServiceContext = (container: IContainer) => new ServiceContext<ITransactionKeywordRepositoryService>(container, $TransactionKeywordRepositoryService);
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_m0h32cs8mlsm7kqx64e3iug0 = true;