/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IFileSource} from "@leight/file";
import {FileBasePrismaSource} from "../PrismaSource/FilePrismaSource";

export class FileSource extends FileBasePrismaSource implements IFileSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ks1br2n9k8fo5wziv7v6q0y4 = true;