/**
 This is a file generated by MCP (managed code pattern) approach.

 So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
    AbstractSourceMapper,
    type ISourceMapper
}                            from "@leight/source-server";
import {
    type ITransactionSource,
    type ITransactionSourceSchema
}                            from "@monye.one/transaction";
import {TransactionSourceEx} from "../source";

export type ITransactionSourceMapper = ISourceMapper<ITransactionSourceSchema>;

export class TransactionSource extends TransactionSourceEx implements ITransactionSource {
}

export class TransactionSourceMapper extends AbstractSourceMapper<ITransactionSourceSchema> implements ITransactionSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_i9t1d2m3e6cik7inyifb8mqm = true;
