/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITransactionSource} from "@monye.one/transaction";
import {TransactionBaseSource} from "./ServerBaseSource";

export class TransactionSource extends TransactionBaseSource implements ITransactionSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_m2okmiqp4z16rftpnxq9e6o9 = true;