/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {withSourceProcedure} from "@leight/trpc-source-server";
import {
	$TransactionSource,
	TransactionQuerySchema,
	type ITransactionSourceSchema
} from "@monye.one/transaction";

export const TransactionSourceProcedure = withSourceProcedure<ITransactionSourceSchema>({
    source: $TransactionSource,
    schema: TransactionQuerySchema,
});