/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IQueryProviderProps,
	QueryProvider
} from "@leight/source-client";
import {type IFilterSourceSchema as SourceSchema} from "@leight/filter";
import {type FC} from "react";
import {FilterSource as Source} from "../source/FilterSource";

export interface IFilterQueryProviderProps extends Omit<IQueryProviderProps<SourceSchema>, "QueryContext"> {
}

/**
 * Provides all Query parts for Filter used in fetching and sorting its data. 
 */
export const FilterQueryProvider: FC<IFilterQueryProviderProps> = props => {
    return <QueryProvider<SourceSchema>
        QueryContext={Source.query}
        {...props}
    />;
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_plbj762be76x9dk2mhf9kojv = true;