/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ISource} from "@leight/source";
import {type IFileSourceSchema as SourceSchema} from "../schema/IFileSourceSchema";

export type IUseFileRepository = ISource.IUseRepository<SourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_a2h867enjdjdhe1zy8hf6opp = true;