/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type FileSource} from "../../schema";

export type UseFileRepositoryQuery = FileSource["Type"]["UseRepositoryQuery"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ujx3wf3e8wvj7p4sq0vyqlum = true;