module.exports = {
    extends: [
        "eslint:recommended",
        "next",
        "airbnb",
        "airbnb-typescript",
        "prettier",
        "turbo",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
    ],
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "./tsconfig.json",
    },
    plugins: ["@typescript-eslint", "eslint-plugin-unicorn", "disable"],
    rules: {
        "import/prefer-default-export": "off",
        "react/react-in-jsx-scope": "off",
        "no-console": "off",
        "import/extensions": "off",
        "arrow-body-style": "off",
        "react/jsx-curly-brace-presence": "off",
        "react/jsx-props-no-spreading": "off",
        "react/function-component-definition": "off",
        "no-underscore-dangle": "off",
        "@typescript-eslint/no-shadow": "off",
        "@typescript-eslint/no-explicit-any": "off",
        "class-methods-use-this": "off",
        "@typescript-eslint/no-empty-interface": "off",
        "react-hooks/exhaustive-deps": "off",
        "no-unused-vars": "off",
        "@next/next/no-html-link-for-pages": "off",
        "no-await-in-loop": "off",
        "no-plusplus": "off",
    },
    settings: {
        react: {
            version: "18",
        },
    },
};
