/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type TransactionSource} from "../../schema";

export type ITransactionSourceType = TransactionSource["Type"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_w2eiyyt6yej5az8fsmq4rq23 = true;