/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type TransactionSource} from "../../schema";

export type ITransactionSource = TransactionSource["Type"]["Source"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_evorkuxhuj06aa6j7y7et8a6 = true;