/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IKeywordSourceService,
	KeywordBaseSourceService
} from "./KeywordBaseSourceService";

export class KeywordSourceService extends KeywordBaseSourceService implements IKeywordSourceService {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_myop3lp9ubcnr7n00ok4lgvc = true;