/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createMultiSelectionStore} from "@leight/selection-client";
import {type IStoreContext} from "@leight/context";
import {type IMultiSelectionStoreProps} from "@leight/selection";
import {type ILabelSourceSchemaType} from "@leight/label";

export type ILabelMultiSelectionStore = IStoreContext<IMultiSelectionStoreProps<ILabelSourceSchemaType["Dto"]>>;

export const LabelMultiSelection = createMultiSelectionStore<ILabelSourceSchemaType["Dto"]>({name: "Label"});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_f0aib90djl212u3u01oh3skl = true;