/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceMapper} from "@leight/source-server";
import {
	type ICalendarEventSourceSchemaType,
	type ICalendarEventSourceMapper
} from "@monye.one/book";

export class CalendarEventBaseSourceMapper extends AbstractSourceMapper<ICalendarEventSourceSchemaType> implements ICalendarEventSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_swgu3agd0i0dygako2390vkw = true;