/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IKeywordSourceMapper} from "@leight/keyword";
import {KeywordBaseSourceMapper} from "./KeywordBaseSourceMapper";

export class KeywordSourceMapper extends KeywordBaseSourceMapper implements IKeywordSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_i99y4pyqta9g5ho9a180s3mr = true;