/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceMapper} from "@leight/source-server";
import {
	type IKeywordSourceSchemaType,
	type IKeywordSourceMapper
} from "@leight/keyword";

export class KeywordBaseSourceMapper extends AbstractSourceMapper<IKeywordSourceSchemaType> implements IKeywordSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hcsonzxd07eeg3ouwjbcs9zw = true;