/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUserSourceSchema} from "@leight/user";
import {type ISourceMapper} from "@leight/source-server";

export type IUserSourceMapper = ISourceMapper<IUserSourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_poidefe7l3k2kzwn3mlgaxjl = true;