/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUserSourceSchemaType} from "@leight/user";
import {type ISourceMapper} from "@leight/source";

export type IUserSourceMapper = ISourceMapper<IUserSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_p1o7gr8e1u29k4et8u1f8f1z = true;