/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IJobSource} from "@leight/job";
import {JobBaseSource} from "./JobBaseSource";

export class JobSource extends JobBaseSource implements IJobSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_vkj58ulbc5vmpsr3t70fz9dd = true;