/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IMantineFormContext} from "@leight/form";
import {type IBankPatchFormSchemaType} from "../../schema/BankPatchFormSchema";

export type IBankPatchMantineFormContext = IMantineFormContext<IBankPatchFormSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_moiwnk7l5t48wde263ihi91f = true;