/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $FileRepository = Symbol.for("@leight/file/IFileRepository");
export const $FileRepositoryMapper = Symbol.for("@leight/file/IFileRepositoryMapper");
export const $FileRepositoryService = Symbol.for("@leight/file/IFileRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_dg5kbv0shx1li55gmhezt0mc = true;