/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IFileSourceMapper} from "@leight/file";
import {FileBaseSourceMapper} from "./FileBaseSourceMapper";

export class FileSourceMapper extends FileBaseSourceMapper implements IFileSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_zip31di9ndgs79r84l8f2rex = true;