/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryMapper} from "@leight/source";
import {type KeywordSource} from "../../schema";

export interface IKeywordRepositoryMapper extends IRepositoryMapper<KeywordSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_z249p0edznjclf7k4lj47t1e = true;