/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUserSourceMapper} from "../api/UserTypes";
import {UserBaseSourceMapper} from "./UserBaseSourceMapper";

export class UserSourceMapper extends UserBaseSourceMapper implements IUserSourceMapper {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hgyt4o5ot8f2sdyi2ho2ob2s = true;