/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	DtoForm as BaseForm,
	type IDtoFormProps as IBaseFormProps
} from "@leight/form-client";
import {type FC} from "react";
import {
	type ILabelPatchFormSchemaType,
	LabelPatchFormSchema
} from "@leight/label";
import {LabelPatchFormStoreContext} from "../FormStoreContext/LabelPatchFormStoreContext";
import {LabelPatchMantineFormContext} from "../FormStoreContext/LabelPatchMantineFormContext";

export interface ILabelPatchBaseFormProps extends Omit<IBaseFormProps<ILabelPatchFormSchemaType>, "FormContext" | "MantineContext" | "withTranslation"> {
}

export const LabelPatchBaseForm: FC<ILabelPatchBaseFormProps> = props => {
    return <BaseForm<ILabelPatchFormSchemaType>
        MantineContext={LabelPatchMantineFormContext}
        schemas={LabelPatchFormSchema}
        FormContext={LabelPatchFormStoreContext}
        withTranslation={{
            namespace: "label",
            label:     "LabelPatchBaseForm",
        }}
        {...props}
    />;
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ahtup4w74vhyfxkbffshbz4p = true;