/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepository} from "@leight/source";
import {type BankSource} from "../../schema";

export interface IBankRepository extends IRepository<BankSource["Schema"]["Repository"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_a63e3i3534yyudpe0c2v2ype = true;