/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type BankSource} from "../../schema";

export type UseBankRepositoryQuery = BankSource["Type"]["UseRepositoryQuery"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_z68ia4ed7w0m7veft44x5xp2 = true;