/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type CalendarEventSource} from "../../schema";

export type ICalendarEventSourceSchema = CalendarEventSource["Schema"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_qmlly2gkog4ubrkgayb0adxo = true;