/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	WithIdentitySchema,
	WithOptionalIdentitySchema
} from "@leight/source";
import {
	router,
	procedure
} from "../../router";
import {FilterSourceSchema} from "@leight/filter";
import {FilterSourceProcedure} from "@leight/filter-server";

export const FilterSourceRouter = router({
    create: procedure
                .input(FilterSourceSchema.ToCreateSchema)
                .mutation(FilterSourceProcedure.handleCreate),
    patch:  procedure
                .input(FilterSourceSchema.ToPatchSchema)
                .mutation(FilterSourceProcedure.handlePatch),
    delete:  procedure
                .input(WithIdentitySchema)
                .mutation(FilterSourceProcedure.handleDelete),
    deleteWith:  procedure
                .input(FilterSourceSchema.QuerySchema)
                .mutation(FilterSourceProcedure.handleDeleteWith),
    query:  procedure
                .input(FilterSourceSchema.QueryOptionalSchema)
                .query(FilterSourceProcedure.handleQuery),
    count:  procedure
                .input(FilterSourceSchema.QueryOptionalSchema)
                .query(FilterSourceProcedure.handleCount),
    fetch:  procedure
                .input(FilterSourceSchema.QuerySchema)
                .query(FilterSourceProcedure.handleFetch),
    find:   procedure
                .input(WithIdentitySchema)
                .query(FilterSourceProcedure.handleFind),
    findOptional:   procedure
                .input(WithOptionalIdentitySchema)
                .query(FilterSourceProcedure.handleFindOptional),
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hvayr1wrrbljykfrb9zhcw04 = true;