/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositorySchemaEx} from "@leight/source";
import {z} from "@leight/utils";

export type IFilterRepositorySchemaEx = IRepositorySchemaEx<
    any,
    any,
    any
>;
export type IFilterRepositoryExType = IFilterRepositorySchemaEx["Type"];
export type IFilterRepositoryExSchema = IFilterRepositorySchemaEx["Schema"];

export const FilterRepositorySchemaEx: IFilterRepositoryExSchema = {
    WhereSchema:       z.object({}),
    WhereUniqueSchema: z.object({}),
    OrderBySchema:     z.object({}),
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_d6u3punwoca7r70lq61kmdpp = true;