/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IFileSourceService,
	FileBaseSourceService
} from "./FileBaseSourceService";

export class FileSourceService extends FileBaseSourceService implements IFileSourceService {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_sud17ndel9x17mg9dzhx1651 = true;