/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepository} from "@leight/source";
import {type UserSource} from "../../schema";

export interface IUserRepository extends IRepository<UserSource["Schema"]["Repository"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ixbc4r3nvqyvo4cjzl8s027h = true;