/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IUseRepositoryQuery} from "@leight/source";
import {type IUserSourceSchema as SourceSchema} from "../schema/IUserSourceSchema";

export type IUseUserRepositoryQuery = IUseRepositoryQuery<SourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_boai4enlvy2k7zmnlqavc3b1 = true;