/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type UserSource} from "../../schema";

export type UseUserRepository = UserSource["Type"]["UseRepository"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ueac27szm0j4fu8p9eengqa2 = true;