/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ISource} from "@leight/source";
import {type IJobSourceSchema as SourceSchema} from "../schema/IJobSourceSchema";

export type IJobSource = ISource<SourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_lurdks8ml8lqqxi80ghh0qhj = true;