/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type JobSource} from "../../schema";

export type IJobSourceSchema = JobSource["Schema"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_iz7mwbr6t3d9f9s6kd42lsy8 = true;