/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractRepositoryService} from "@leight/source-server";
import {
	type IRepositoryService,
	type IRepositoryMapper,
	type IRepository
} from "@leight/source";
import {
	$TransactionRepository,
	$TransactionRepositoryMapper,
	type TransactionSource
} from "@monye.one/transaction";

export interface ITransactionRepositoryService extends IRepositoryService<TransactionSource["Schema"]["Service"]> {
}

export class BaseTransactionRepositoryService<
    TServiceSchema extends TransactionSource["Schema"]["Service"] = TransactionSource["Schema"]["Service"]
> extends AbstractRepositoryService<TServiceSchema> implements ITransactionRepositoryService {
	static inject = [
        $TransactionRepository,
        $TransactionRepositoryMapper,
    ];
    
    constructor(
        protected $repository: IRepository<TServiceSchema>,
        protected $mapper: IRepositoryMapper<TServiceSchema>,
    ) {
        super();
    }

    mapper(): IRepositoryMapper<TServiceSchema> {
        return this.$mapper;
    }
    
    repository(): IRepository<TServiceSchema> {
        return this.$repository;
    }
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_n6l85b3mveew5xggro9alnuy = true;