/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type KeywordSource} from "../../schema/KeywordSource";

export type IKeywordSourceSchema = KeywordSource["Schema"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hk8n84bsm4aq9v6iyosq8l4k = true;