/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositorySchemaEx} from "@leight/source";
import {z} from "@leight/utils";

export type IKeywordRepositorySchemaEx = IRepositorySchemaEx<
    any,
    any,
    any
>;
export type IKeywordRepositoryExType = IKeywordRepositorySchemaEx["Type"];
export type IKeywordRepositoryExSchema = IKeywordRepositorySchemaEx["Schema"];

export const KeywordRepositorySchemaEx: IKeywordRepositoryExSchema = {
    WhereSchema:       z.object({}),
    WhereUniqueSchema: z.object({}),
    OrderBySchema:     z.object({}),
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_og2pqm0m242kgf2opz29uhcl = true;