/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $LabelRepository = Symbol.for("@leight/label/ILabelRepository");
export const $LabelRepositoryMapper = Symbol.for("@leight/label/ILabelRepositoryMapper");
export const $LabelRepositoryService = Symbol.for("@leight/label/ILabelRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_gbpggk3gu0ei1e5e12p8537k = true;