/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_s1rfb2lu3rllqk70cayn5rmn = true;

export * from "./ClientSource/CalendarEventQueryProvider";
export * from "./ClientSource/CalendarEventSource";
export * from "./ClientSource/CalendarEventSourceStore";
export * from "./ClientTrpc/UseCalendarEventSourceQuery";