/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_h23mk2pabw8gi0gddrveihd0 = true;

export * from "./index";
export * from "./container/withCalendarEventRepositoryContainer";
export * from "./repository/BaseCalendarEventRepository";