/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_oaoflksukea77pftyp6f0145 = true;

export * from "./api/CalendarEventTypes";
export * from "./BaseSource/CalendarEventBaseSource";
export * from "./ServerSource/CalendarEventServerSource";
export * from "./ServerSourceMapper/CalendarEventBaseSourceMapper";
export * from "./ServerSourceMapper/CalendarEventSourceMapper";
export * from "./ServerSourceService/CalendarEventBaseSourceService";
export * from "./ServerSourceService/CalendarEventSourceService";
export * from "./ServerTrpc/CalendarEventTrpc";