/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ICalendarEventSource} from "@monye.one/book";
import {CalendarEventBaseSource} from "./ServerBaseSource";

export class CalendarEventSource extends CalendarEventBaseSource implements ICalendarEventSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_raiqpljbuxdn91hcf3n6fw60 = true;