/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ICalendarEventSource} from "@monye.one/book";
import {CalendarEventBaseSourceEx} from "../source";

export class CalendarEventSource extends CalendarEventBaseSourceEx implements ICalendarEventSource {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ikm7z2lwqgaq1jpohunnr3mn = true;