/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createMantineFormContext} from "@leight/form-client";
import {type ITransactionFilterFormSchema} from "@monye.one/transaction";

export const TransactionFilterMantineFormContext = createMantineFormContext<ITransactionFilterFormSchema>();
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_oyx0th9p3kqbxcq68ydwuqd6 = true;