/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {createFormContext} from "@leight/form-client";
import {type ITransactionFilterFormSchema} from "@monye.one/transaction";

export const TransactionFilterFormStoreContext = createFormContext<ITransactionFilterFormSchema>({
    name: "TransactionFilterForm",
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_nx7ex57r0y34ypj6ksmn7zd6 = true;