/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type KeywordSource} from "../../schema";

export type IKeywordSource = KeywordSource["Type"]["Source"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ip3t1kng6ttcn0h6uljyayij = true;