/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $BankRepository = Symbol.for("@monye.one/bank/IBankRepository");
export const $BankRepositoryMapper = Symbol.for("@monye.one/bank/IBankRepositoryMapper");
export const $BankRepositoryService = Symbol.for("@monye.one/bank/IBankRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_qk6stk0vkqfez3q9ofdh07ts = true;