/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $TransactionKeywordRepository = Symbol.for("@monye.one/transaction/ITransactionKeywordRepository");
export const $TransactionKeywordRepositoryMapper = Symbol.for("@monye.one/transaction/ITransactionKeywordRepositoryMapper");
export const $TransactionKeywordRepositoryService = Symbol.for("@monye.one/transaction/ITransactionKeywordRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_zkzhbq6g75p5hitebdqqrd30 = true;