/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $TransactionRepository = Symbol.for("@monye.one/transaction/ITransactionRepository");
export const $TransactionRepositoryMapper = Symbol.for("@monye.one/transaction/ITransactionRepositoryMapper");
export const $TransactionRepositoryService = Symbol.for("@monye.one/transaction/ITransactionRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_pbnevh3ya8ezqwxmqs7lja57 = true;