/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceService} from "@leight/source-server";
import {
	type ISourceService,
	type ISourceMapper,
	type ISource
} from "@leight/source";
import {
	$CalendarEventSource,
	$CalendarEventSourceMapper,
	type ICalendarEventSourceSchema
} from "@monye.one/book";

export interface ICalendarEventSourceService extends ISourceService<ICalendarEventSourceSchema> {
}

export class CalendarEventBaseSourceService extends AbstractSourceService<ICalendarEventSourceSchema> implements ICalendarEventSourceService {
	static inject = [
        $CalendarEventSource,
        $CalendarEventSourceMapper,
    ];
    
    constructor(
        protected $source: ISource<ICalendarEventSourceSchema>,
        protected $mapper: ISourceMapper<ICalendarEventSourceSchema>,
    ) {
        super();
    }
    
    source(): ISource<ICalendarEventSourceSchema> {
        return this.$source;
    }
    
    mapper(): ISourceMapper<ICalendarEventSourceSchema> {
        return this.$mapper;
    }
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_lqt1t5wfj8j8y5fvrag8uglh = true;