/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IUserSourceService,
	UserBaseSourceService
} from "./UserBaseSourceService";

export class UserSourceService extends UserBaseSourceService implements IUserSourceService {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_pnj7lfdlk22tra0ire89qewr = true;