/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {AbstractSourceService} from "@leight/source-server";
import {
	type ISourceService,
	type ISourceMapper,
	type ISource
} from "@leight/source";
import {
	$UserSource,
	$UserSourceMapper,
	type IUserSourceSchema
} from "@leight/user";

export interface IUserSourceService extends ISourceService<IUserSourceSchema> {
}

export class UserBaseSourceService extends AbstractSourceService<IUserSourceSchema> implements IUserSourceService {
	static inject = [
        $UserSource,
        $UserSourceMapper,
    ];
    
    constructor(
        protected $source: ISource<IUserSourceSchema>,
        protected $mapper: ISourceMapper<IUserSourceSchema>,
    ) {
        super();
    }
    
    source(): ISource<IUserSourceSchema> {
        return this.$source;
    }
    
    mapper(): ISourceMapper<IUserSourceSchema> {
        return this.$mapper;
    }
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_c1zkyz7yf3qcpif064wwtda6 = true;