/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IBankSourceSchemaType} from "../schema/BankSourceSchema";
import {type ISourceMapper} from "@leight/source";

export type IBankSourceMapper = ISourceMapper<IBankSourceSchemaType>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_xotf9b0jugu4ys5x4l08bg9p = true;