/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	type IMantineFormContext,
	type IFormInputsFactory
} from "@leight/form";
import {type IBankPatchFormSchema} from "../schema/BankPatchFormSchema";

export type IBankPatchMantineFormContext = IMantineFormContext<IBankPatchFormSchema>;
export type IBankPatchFormInputFactory = IFormInputsFactory<IBankPatchFormSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hs7cxukbmxt4ufwtm5lipci5 = true;