/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IRepositoryService} from "@leight/source";
import {type ICalendarEventSourceSchema as SourceSchema} from "../schema/ICalendarEventSourceSchema";

export type ICalendarEventRepositoryService = IRepositoryService<SourceSchema>;

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_yo79jsxtbuj6ezoae6uq5wdp = true;