/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $JobRepository = Symbol.for("@leight/job/IJobRepository");
export const $JobRepositoryMapper = Symbol.for("@leight/job/IJobRepositoryMapper");
export const $JobRepositoryService = Symbol.for("@leight/job/IJobRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_um8yyr4txph0wf0d4kxf5o21 = true;