/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
	WithIdentitySchema,
	WithOptionalIdentitySchema
} from "@leight/source";
import {
	router,
	procedure
} from "../../router";
import {FilterSourceSchema} from "@leight/filter";
import {FilterRepositoryHandler} from "@leight/filter-server";

export const FilterRepositoryRouter = router({
    create: procedure
                .input(FilterSourceSchema.CreateSchema)
                .mutation(FilterRepositoryHandler.handleCreate),
    patch:  procedure
                .input(FilterSourceSchema.PatchSchema)
                .mutation(FilterRepositoryHandler.handlePatch),
    patchBy:  procedure
                .input(FilterSourceSchema.PatchBySchema)
                .mutation(FilterRepositoryHandler.handlePatchBy),
    upsert:  procedure
                .input(FilterSourceSchema.UpsertSchema)
                .mutation(FilterRepositoryHandler.handleUpsert),
    delete:  procedure
                .input(FilterSourceSchema.DeleteSchema)
                .mutation(FilterRepositoryHandler.handleDelete),
    deleteBy:  procedure
                .input(FilterSourceSchema.DeleteBySchema)
                .mutation(FilterRepositoryHandler.handleDeleteBy),
    query:  procedure
                .input(FilterSourceSchema.QuerySchema)
                .query(FilterRepositoryHandler.handleQuery),
    count:  procedure
                .input(FilterSourceSchema.CountSchema)
                .query(FilterRepositoryHandler.handleCount),
    fetch:  procedure
                .input(FilterSourceSchema.FetchSchema)
                .query(FilterRepositoryHandler.handleFetch),
    fetch$:  procedure
                .input(FilterSourceSchema.Fetch$Schema)
                .query(FilterRepositoryHandler.handleFetch$),
    get:   procedure
                .input(WithIdentitySchema)
                .query(FilterRepositoryHandler.handleGet),
    get$:   procedure
                .input(WithOptionalIdentitySchema)
                .query(FilterRepositoryHandler.handleGet$),
});
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_a8i5plp4h8b4h6c41fku6j0x = true;