/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type JobSource} from "../../schema";

export type UseJobRepositoryQuery = JobSource["Type"]["UseRepositoryQuery"];

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_mjt9i87dada97i90kl7x2gr6 = true;