/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type ITrpcFormProps} from "@leight/form";
import {BlockStore} from "@leight/utils-client";
import {type ILabelPatchFormSchemaType} from "@leight/label";
import {type FC} from "react";
import {
	type ILabelPatchBaseFormProps,
	LabelPatchBaseForm
} from "../Form/LabelPatchBaseForm";
import {useLabelQueryInvalidator} from "./useLabelQueryInvalidator";
import {UseLabelSourceQuery} from "./UseLabelSourceQuery";

export interface ILabelPatchTrpcFormProps extends ILabelPatchBaseFormProps, ITrpcFormProps<ILabelPatchFormSchemaType> {
}

export const LabelPatchTrpcForm: FC<ILabelPatchTrpcFormProps> = ({onSuccess, onError, onSettled, ...props}) => {
    const {block} = BlockStore.useOptionalState() || {block: () => null};
    const mutation = UseLabelSourceQuery.usePatch();
    const invalidator = useLabelQueryInvalidator();
    return <LabelPatchBaseForm
        onSubmit={({request, onDefaultSubmit}) => {
            block(true);
            mutation.mutate(request, {
                onSuccess: dto => {
                    onDefaultSubmit();
                    invalidator();
                    onSuccess?.({dto});
                },
                onError: error => {
                    onError?.({error});                    
                },
                onSettled: () => {
                    block(false);
                    onSettled?.({});
                },
            });
        }}
        {...props}
    />;
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ez8qjltaeej2o6nopzzwxuqc = true;